### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by frankpinto** [claviska/jquery-dropdown#106]
I'd like to use this plugin with Browserify and that's easier when its published to npm. The repo already has a package.json, is there anything else needed aside from a `npm publish`?

**Comment by jingzhou123** [comment]
+1

**Comment by sg1303** [comment]
+1

**Comment by anbiniyar** [comment]
+1

**Comment by claviska** [comment]
https://www.npmjs.com/package/@claviska/jquery-dropdown
