### ISSUE TITLE
Toggle Triggerclass onclick

### ISSUE THREAD

**Issue by DevidraEX** [claviska/jquery-dropdown#108]
I know there is a "toggleclass" but im pretty new to this and hope I will get some help from you

I've created allready the CSS for ;hover / class.hover, it work fine if I put it manually through the console

Now is the problem, how can I add this to the "click" element so if the dropdown is visible the trigger element get the "hover" class and if not remove?

**Comment by claviska** [comment]
Sorry for the late response. There's no way to do this through the API. You'd have to tap into the trigger with JavaScript to add/remove the class.
