### ISSUE TITLE
Scss implementation

### ISSUE THREAD

**Issue by sg1303** [claviska/jquery-dropdown#110]
What do you think about having an scss file in the project as well for those whose projects only use sass?

**Comment by claviska** [comment]
My newest project is using Sass too. I'll accept a PR if you want to do the [relatively simple] conversion :)

**Comment by sg1303** [comment]
Done!
https://github.com/claviska/jquery-dropdown/pull/111

**Comment by sg1303** [comment]
Did you prefer to have both less and sass? I think I read your wording "conversion" meaning to completely convert. I can add the less file back too if you want.

**Comment by claviska** [comment]
Should have clarified...let's leave the Less version there until the next major version to prevent a breaking change. I'll update the Sass file as needed until then :)

**Comment by sg1303** [comment]
OK, I went ahead and added that back and updated the codekit config file. Please take a look.
