### ISSUE TITLE
Page with menu canvas

### ISSUE THREAD

**Issue by kamov** [claviska/jquery-dropdown#121]
Hi,
I am using http://mmenu.frebsite.nl/ on my site, and when menu is open per default (in large screen), then dropdown appear on right side.

Any idea how to fix this?

![screen shot 2017-03-10 at 10 11 06](https://cloud.githubusercontent.com/assets/2345000/23789180/effaa95e-0579-11e7-92a9-2cbbdf7744a1.png)

Thanks!

**Comment by claviska** [comment]
Please post a minimal example or a Fiddle, otherwise we're just speculating :)

**Comment by kamov** [comment]
Sure, I make here an example page: http://goo.gl/g8no2o

You should resize browser more than 1200px, so sidebar menu is open

Thanks for checking!

**Comment by pallxk** [comment]
Adding class `jq-dropdown-relative` to your jq-dropdown solves it.

Though I'm not sure if current behavior is expected as the document says

> To position a jq-dropdown relative to its parent (as opposed to the document), add the `jq-dropdown-relative` class to the jq-dropdown container.

But I found that whether `jq-dropdown-relative` is specified, jq-dropdown is always positioned against the closest ancestor element that is positioned.

The difference is that if `jq-dropdown-relative` is specified, the position is calculated as related to the closest positioned ancestor, which matches the positioning logic;

while if that's not specified, the position is calculated as related to the document, which may be inconsistent with the positioning logic, if the closest positioned ancestor is not the document.

**Comment by kamov** [comment]
Thanks!! That solved the issue... I am not sure why I don't find it when I looked in documentation...
