### ISSUE TITLE
Submenu with css

### ISSUE THREAD

**Issue by kamov** [claviska/jquery-dropdown#122]
Using only CSS you could add submenu, see:

![screen shot 2017-03-10 at 10 30 01](https://cloud.githubusercontent.com/assets/2345000/23789786/9ebca300-057c-11e7-8cde-c9e0478bf2ee.png)

Similar like this: http://bootsnipp.com/snippets/featured/multi-level-dropdown-menu-bs3

**Comment by claviska** [comment]
Thanks for the heads up. Hopefully it will help someone, but at this time I have no interest in supporting submenus.

**Comment by kamov** [comment]
Thanks to you for the plugin, it's perfect as-is now. I just need submenu so I look into.
You can find here working demo with your plugin: https://jsfiddle.net/45qu1pwx/3/
It require to clean css code taken from bootstrap, but works fine.
