### ISSUE TITLE
Dropdown buttons on ajax.

### ISSUE THREAD

**Issue by MarkSamp** [claviska/jquery-dropdown#125]
Hi, i have some dropdown buttons that are loaded by jquery ajax. How can i force the plugin to get this new dropdown buttons to work? Thanks in advance.

**Comment by claviska** [comment]
See the API section [in the docs](http://labs.abeautifulsite.net/jquery-dropdown/):

```js
$('#trigger').jqDropdown('attach', '#menu-id');
```
