### ISSUE TITLE
show hide programmatically

### ISSUE THREAD

**Issue by brackmayhall** [claviska/jquery-dropdown#64]
I am not having any luck with the show hide calls. All other trigger calls work fine. Below is how I am calling them.

        $('#testInput').dropdown('attach','#dropdown-1');        // PASS
        $('#testInput').dropdown('detach','#dropdown-1');       // PASS
        $('#testInput').dropdown('show','#dropdown-1');         // FAIL
        $('#testInput').dropdown('hide','#dropdown-1');           // FAIL
        $('#testInput').dropdown('enable','#dropdown-1');       // PASS
        $('#testInput').dropdown('disable','#dropdown-1');       // PASS

Any idea what im doing wrong here??

**Comment by jquimera** [comment]
@claviska 
```
$("#showButton").click(function(event){
    event.stopPropagation();
    $('#testInput').dropdown('show');
});
```
This is interesting, I like the dropdown does not close with the right click.

Can you help me? Thanks!
