### ISSUE TITLE
conflict with dropdown-menu

### ISSUE THREAD

**Issue by dcy** [claviska/jquery-dropdown#68]
<ul class="nav navbar-nav navbar-right">
        {% if account %}
          <li><a href="#" data-dropdown="#dropdown-1"><i class="fa fa-bell"></i>提醒<span class="badge"></span></a></li>
          <li><a href="#"><i class="fa fa-envelope"></i>邮件<span class="badge">36</span></a></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user fa-fw"></i>{{ account.name }}的账户 <b class="caret"></b></a>
          <ul class="dropdown-menu col-sm-1">
            <li><a href="/account/{{ account.id }}"><i class="fa fa-home fa-fw"></i>我的主页</a></li>
            <li><a href="/account/profile"><i class="fa fa-cog fa-fw"></i>我的账号</a></li>
            <li><a href="/account/logout"><i class="fa fa-power-off fa-fw"></i>退出</a></li>
          </ul>
          </li>
        {% else %}
It is my html, when i click one dropdown, the last dropdown will disappear. the <a> tag will disappear.

**Comment by claviska** [comment]
Fixed in 2.0.0.

**Comment by dcy** [comment]
Where is 2.0.0?
I see 1.0.6, no 2.0.0

**Comment by kaymer327** [comment]
If you pull the latest code from the [main project] (https://github.com/claviska/jquery-dropdown), you will get 2.0.0.

2.0.0 hasn't been created in the releases section yet which is why you don't see it there.

**Comment by claviska** [comment]
Whoops, forgot to add the 2.0.0 tag. Updated.
