### ISSUE TITLE
Dropdown positioning when the trigger has a parent with position:relative

### ISSUE THREAD

**Issue by petrasitis** [claviska/jquery-dropdown#70]
If your trigger has a parent with position:relative the dropdown appears in the wrong position. I tried dropdown-relative but still no difference. I don't know if it matters but the trigger is in a modal.

The only solution was to remove position:relative from all the parents which isn't practical.

Any ideas.

**Comment by web2feel** [comment]
The relative positioned parent element of the trigger pushes the dropdown panel further away.  Is there any fix?

**Comment by skmasq** [comment]
Workaround I came up with was to do an absolute wrap around the dropdown to adjust the position.

**Comment by claviska** [comment]
A new version of this plugin will rework positioning entirely so this won't be an issue. Closing due to age.
