### ISSUE TITLE
Dropdown overlaps with modal dialog (bootbox)

### ISSUE THREAD

**Issue by bartvanderwal** [claviska/jquery-dropdown#73]
My [fork](https://github.com/bartvanderwal/jquery-dropdown) now works better along with Bootstrap thanks to some simple renaming. But I still bumped into an issue with overlapping content with Bootstrap's [Bootbox plugin](https://github.com/makeusabrew/bootbox) due to a very high [z-index](https://github.com/claviska/jquery-dropdown/blob/aae74dc7f2b0ce210e43e9532fce72bcce44bc13/jquery.dropdown.css) used in this projects CSS (line 3):
See below screenshot.

I expect the dropdown panel to be below the modal dialog, and also behind it's mask.

Disabling the z-index fixed this issue. However it caused some other issues later. Is there a structured way of handling z-index-es dynamically or something, instead of just setting it REALLY high? :smile: 

```css
.dropdown {
   position: absolute;
   /* z-index: 9999999; */
   display: none;
}
```

![jquerydropdownzindexbugwithbootboxmodal](https://cloud.githubusercontent.com/assets/3029472/5394874/de57cdde-8142-11e4-8ee8-593d64b0e523.png)

**Comment by claviska** [comment]
Fixed in 2.0.0.
