### ISSUE TITLE
Dynamically created select dropdown did not work

### ISSUE THREAD

**Issue by sivailango** [claviska/jquery-dropdown#74]
Hi,
       I am using jquery-dropdown with bootstrap material design. When i was trying to clone particular row which includes select dropdown, cloned select element does not work. It does not shows options.

I added below one in document ready,
$('select').dropdown({'optionClass': 'withripple'});	

Below code takes clone of current row and create new one. But select drop down did not work how i expected.

$('#add-company-user').on('click', '.add-more-user', function() {
		$(this).closest('.row-company-user > .row').eq(0).clone().find('.clone-clear').val('').end().appendTo('.row-company-user');

});

**Comment by claviska** [comment]
The plugin shows the target menu as it is in the DOM. This seems like an implementation issue, not a bug.
