### ISSUE TITLE
Jquery dropdown inside an asp.net .ascx User control..inside jquery ui popup dialog

### ISSUE THREAD

**Issue by mnichols1202** [claviska/jquery-dropdown#78]
racking my brain over this....Nice plugin BTW.
I have a large section of a page that turns out is repeated exactly across several pages in my site.
So it is  real convenient to turn that part into an .ASCX User Control.
This section actually pops up when the user selects some criteria so i plop the ASCX into either a panel with an AJAX Modal Popup Extender or alternatively a JQuery UI Dialog . 
Works perfect up to the point i use the modal popup extender or  Jquery UI Dialog.
the Dropdowns then display inside the dialog  offset from the trigger controls exactly the distance that the "popup" is offset from the upper left corner of the browser window.

so if the upper left cornet of the Popup is as offset 100 pixes right and 50 pixels down from the upper left edge of the parent window the dropdowns will display 100 pixels to the right and 50 pixels below  the controls they are anchored to.  any ideas?  thanks in advance.

**Comment by mnichols1202** [comment]
It looks like my issue is related to issue #70 ......if it's a dup please just close this with my apologies and  i'll just continue to follow #70....thanks.

**Comment by claviska** [comment]
Seems like a dup. Please follow #70
