### ISSUE TITLE
Hmmm. How about naming it without the "hyphen"....(minus sign)

### ISSUE THREAD

**Issue by robvon** [claviska/jquery-dropdown#86]
Good luck trying to get this to behave using the API where the name is taken as "jq" - "dropdown".

Perhaps a "." would be a better alternative

[EDIT] Ok - so I've looked at the code and its called: "jqDropdown". Could you update your doco then - perhaps with some API examples.

**Comment by claviska** [comment]
Docs: http://labs.abeautifulsite.net/jquery-dropdown/

**Comment by robvon** [comment]
I read all of that...

Example usage: $('#trigger').jq-dropdown('method', [value]);

This was the example I used.... Somewhat hyphenated....

Anyway, If using the API:

Do I call
1. Attach
2. Then enable
3. Then trigger (when requested)

**Comment by kaymer327** [comment]
The index.html is correct here on GitHub, but the "live" copy on http://labs.abeautifulsite.net/jquery-dropdown/ doesn't include the fix from #85.

**Comment by claviska** [comment]
The demo site is now up to date. Thanks for catching that.
