### ISSUE TITLE
Bug with preexisting values.

### ISSUE THREAD

**Issue by NVentimiglia** [claviska/jquery-dropdown#88]
Does not respect initial values. For instance I have a form which has a default selection (from a previous submission). This value is correct and present without the plugin. When I apply the plugin the selection is nulled and the .val() is incorrect.

It would be nice if the plugin respected preexisting values.

**Comment by claviska** [comment]
What values are you referring to?

**Comment by NVentimiglia** [comment]
Here is my code.

`````
<select class="form-control select width-150" id="RoleState" name="RoleState"><option value="">Role State</option>
<option value="0">Pending</option>
<option selected="selected" value="1">Approved</option>
<option value="2">Rejected</option>
</select>
`````

After I apply .dropdown() the selection becomes the first (RoleState).

**Comment by claviska** [comment]
This plugin doesn't work on `<select>` elements. Are you posting on the right project?

http://labs.abeautifulsite.net/jquery-dropdown/

**Comment by NVentimiglia** [comment]
Ooh damn, sorry about that.
