### ISSUE TITLE
Not working on iPod and iPad

### ISSUE THREAD

**Issue by flyke** [claviska/jquery-dropdown#93]
The dropdown is not working (when clicking, nothing happens) on iPod and iPad. (maybe also on iPhone but I don't have one to test). It is working fine on desktop and on Android.

Edit:
Seems to work if you add the css style cursor:pointer to your dropdown element.
So probably not a bug of this library, more a general Apple bug or maybe faulty working click events is just an Apple feature. Anyway, with adding cursor:pointer it works.

If someone else has the same problem as me I hope they will easily find this 'solution'.

**Comment by claviska** [comment]
Works fine from all my iOS devices. Likely an implementation issue. If this persists for you, submit a minimal example and I'll take a look.
