### ISSUE TITLE
First click wrong position

### ISSUE THREAD

**Issue by DevidraEX** [claviska/jquery-dropdown#95]
Hi, maybe I messed up the CSS, or I got a bug with the automatic position of the dropdown

I reload a page ( or complete cache ) and click on the trigger for the dropdown

Somehow the position is wrong, I click the trigger again for close and reopen, and now the position is ok.. Strange, any fix for it? And if you need further Information about my CSS etc. just tell me what you need

![wrong](https://cloud.githubusercontent.com/assets/8301472/9242061/360dfcde-417c-11e5-9163-729ab2494dec.jpg)

![correct](https://cloud.githubusercontent.com/assets/8301472/9242063/3a144a36-417c-11e5-8917-0d0aeada8321.jpg)

**Comment by DevidraEX** [comment]
Ok some testing and somehow... It's only occur if the "firebug" and the other "developer tools" from the browser is open

tested in the current IE, FF and GC ( don't have Safari / Opera ), the problem occur in every browser I tried

**Comment by claviska** [comment]
Again, sorry for the late response. I'm not sure this is even an issue anymore, but I'm hoping to rework the way dropdowns are positioned in the next release. If it's still an issue then, feel free to report it.
