### ISSUE TITLE
How to change display to visibility

### ISSUE THREAD

**Issue by zoxon** [claviska/jquery-dropdown#96]
Hello.
I have problems with display: none. How to change display: none to visibility + opacity.
[Perfect-scrollbar](http://noraesae.github.io/perfect-scrollbar/) inside dropdown works not correctly with display: none blocks, but with visibility: hidden works good.
Thank you.

**Comment by claviska** [comment]
It's probably calculating the size while the dropdown is hidden. Try loading it dynamically after the dropdown is shown, or show the dropdown until the scroll plugin is initialized.
